config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :pharmacies
  resources :cosm_meds do
    collection do
      post :import
    end
  end
  resources :cosm_cats
  resources :orders
  resources :categories
  root 'app#index'
  get '/cats', to: 'app#cats'
  get '/prescription', to: 'app#prescription'
  post '/n_prescription', to: 'app#n_prescription'

  get '/checkout', to: 'app#checkout'
  post '/new_order', to: 'app#new_order'
  get '/sales', to: 'orders#sellings'
  post '/sold/:id', to: 'orders#sell'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :medications do
    collection do
      post :import
    end
  end
  resources :cart_items
  get '/cosm_cats/cat/:name', to: 'cosm_cats#cats'
  get '/search', to: 'search#index'
  post '/search', to: 'search#index'

  namespace :api do
    namespace :v1 do
      # Specific to user
      devise_for :users, controllers: { registrations: 'api/v1/registrations' }
      resources :categories, only: %i[index show]
      resources :medications, only: %i[show]
      resources :cosmetics_categories, only: %i[index show]
      resources :cosmetics, only: %i[show]
      resources :cart_items, only: %i[index show create update destroy]
      resources :order_items, only: %i[index]
      resources :orders, only: %i[index create]
      resources :text_orders, only: %i[create]
      resources :img_orders, only: %i[create]
      resources :search, only: %i[index]
      resources :addresses, only: %i[index create destory]
      resources :pharmacy_sessions, only: %i[create]

      # Specific to pharmacies => get orders and classify them
      resources :pharmacy_pending_orders, only: %i[index]
      resources :pharmacy_finished_orders, only: %i[index create]
      resources :pharmacy_not_found_orders, only: %i[create]
      resources :pharmacy_fake_orders, only: %i[create]

      # Specific to the owner => monitor all pharmacies work
      resources :pending_orders, only: %i[index]
      resources :finished_orders, only: %i[index]
      resources :fake_orders, only: %i[index]
      resources :not_found_orders, only: %i[index]
    end
  end
end

app/models/cosm_cat.rb
class CosmCat < ApplicationRecord
  include ImageUploader::Attachment(:image)
  has_many :cosm_meds
end

app/controllers/cosm_cats_controller.rb
# frozen_string_literal: true

class CosmCatsController < ApplicationController
  before_action :set_cosm_cat, only: %i[edit update destroy]
  before_action :authenticate_admin!, except: [:show]

  # GET /cosm_cats or /cosm_cats.json
  def index
    @cosm_cats = CosmCat.all
  end

  # GET /cosm_cats/1 or /cosm_cats/1.json
  def show
    @cosm_cat = CosmCat.find(params[:id])
    @cosm_meds = @cosm_cat.cosm_meds
  end

  def cats
    @cosm_cat = CosmCat.where(parent: params[:name])
  end

  # GET /cosm_cats/new
  def new
    @cosm_cat = CosmCat.new
  end

  # GET /cosm_cats/1/edit
  def edit; end

  # POST /cosm_cats or /cosm_cats.json
  def create
    @cosm_cat = CosmCat.new(cosm_cat_params)

    respond_to do |format|
      if @cosm_cat.save
        format.html { redirect_to @cosm_cat, notice: 'Cosm cat was successfully created.' }
        format.json { render :show, status: :created, location: @cosm_cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cosm_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cosm_cats/1 or /cosm_cats/1.json
  def update
    respond_to do |format|
      if @cosm_cat.update(cosm_cat_params)
        format.html { redirect_to @cosm_cat, notice: 'Cosm cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cosm_cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cosm_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cosm_cats/1 or /cosm_cats/1.json
  def destroy
    @cosm_cat.destroy
    respond_to do |format|
      format.html { redirect_to cosm_cats_url, notice: 'Cosm cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cosm_cat
    @cosm_cat = CosmCat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cosm_cat_params
    params.require(:cosm_cat).permit(:name, :image, :parent)
  end
end

app/helpers/cosm_cats_helper.rb
# frozen_string_literal: true

module CosmCatsHelper
end

app/views/cosm_cats/_form.html.erb
<%= form_with(model: cosm_cat) do |form| %>
<% if cosm_cat.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(cosm_cat.errors.count, "error") %> prohibited this cosm_cat from being saved:</h2>

    <ul>
        <% cosm_cat.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field form-gruop">
    <%= form.label 'الاسم' %>
    <%= form.text_field :name, class:"form-control" %>
</div>

<div class="field form-gruop">
    <%= form.label :parent %>
    <%= form.select :parent, options_for_select(['Makeup', 'Hair Care', 'Baby Care','Vitamins','Fitness Supplements','Skin Care','Household Products', 'Personal Care']), class:"form-control" %>
</div>

<div class="field form-gruop">
    <%= form.label 'الصورة' %>
    <%= form.file_field :image, class:"form-control" %>
</div>

<div class="field form-gruop">
    <%= form.submit 'اضافة قسم', class:'btn btn-success m-2' %>
</div>
<% end %>

app/views/cosm_cats/cats.html.erb
<br><br>
<div class="container max-width3 meds">
    <% @cosm_cat.each do |medication| %>
    <%= link_to cosm_cat_path(medication.id), class:"card-link m-auto" do %>
    <div class="card card2">

        <div class="p-1 pb-0 product-img ">
        <% if medication.image %>
            <%= image_tag medication.image_url %>
        <% end %>    
        </div>

        <div class="product-info p-2 pt-0">
            <h6 class="card-title"><b><%= medication.name %></b></h6>
        </div>
    </div>
    <% end %>
    <% end %>
</div>
<br><br>
<br><br>

app/views/cosm_cats/edit.html.erb
<br>
<div class="max-width2 m-auto p-4">
    <h1>تعديل القسم</h1>

    <%= render 'form', cosm_cat: @cosm_cat %>

    <%= link_to 'Show', @cosm_cat %> |
    <%= link_to 'Back', cosm_cats_path %>

</div>

app/views/cosm_cats/index.html.erb
<h1>Cosm Cats</h1>
<br>
<%= link_to 'اضافة قسم جديد', new_cosm_cat_path, class:"btn-success btn m-3" %>
<br>
<table class="table table-striped m-2" style="font-size:15px;">
    <thead>
        <tr>
            <th>اسم القسم</th>
            <th>الصورة</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @cosm_cats.each do |cosm_cat| %>
        <tr>
            <td><%= cosm_cat.name %></td>
            <td><%= image_tag cosm_cat.image_url, style:"height:50px;" if cosm_cat.image %></td>
            <td><%= link_to 'عرض', cosm_cat, class:"btn btn-secondary" %></td>
            <td><%= link_to 'تعديل القسم', edit_cosm_cat_path(cosm_cat), class:"btn btn-warning" %></td>
            <td><%= link_to 'حذف القسم', cosm_cat, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/cosm_cats/new.html.erb
<br>
<div class="max-width2 m-auto p-4">
    <h1>اضافة قسم جديد</h1>

    <%= render 'form', cosm_cat: @cosm_cat %>

    <%= link_to 'الرجوع', cosm_cats_path, class:'btn btn-secondary m-2' %>
</div>

app/views/cosm_cats/show.html.erb
<br><br>
<div class="container max-width3 meds">
    <% @cosm_meds.each do |medication| %>
    <%= link_to cosm_med_path(medication.id), class:"card-link m-auto" do %>
    <div class="card card3 en">
        <div class="p-1 pb-0 product-img ">
            <%= image_tag medication.image_url if medication.image %>
        </div>
        <div class="product-info p-2 pt-0">
            <h6 class="card-title mb-2"><b><%= medication.name %></b></h6>
            <span class="card-text bg-warning px-1 rounded"><%= medication.price %> EGP</span>
        </div>
    </div>
    <% end %>
    <% end %>
</div>
<br><br>
<br><br>