config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :pharmacies
  resources :cosm_meds do
    collection do
      post :import
    end
  end
  resources :cosm_cats
  resources :orders
  resources :categories
  root 'app#index'
  get '/cats', to: 'app#cats'
  get '/prescription', to: 'app#prescription'
  post '/n_prescription', to: 'app#n_prescription'

  get '/checkout', to: 'app#checkout'
  post '/new_order', to: 'app#new_order'
  get '/sales', to: 'orders#sellings'
  post '/sold/:id', to: 'orders#sell'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :medications do
    collection do
      post :import
    end
  end
  resources :cart_items
  get '/cosm_cats/cat/:name', to: 'cosm_cats#cats'
  get '/search', to: 'search#index'
  post '/search', to: 'search#index'

  namespace :api do
    namespace :v1 do
      # Specific to user
      devise_for :users, controllers: { registrations: 'api/v1/registrations' }
      resources :categories, only: %i[index show]
      resources :medications, only: %i[show]
      resources :cosmetics_categories, only: %i[index show]
      resources :cosmetics, only: %i[show]
      resources :cart_items, only: %i[index show create update destroy]
      resources :order_items, only: %i[index]
      resources :orders, only: %i[index create]
      resources :text_orders, only: %i[create]
      resources :img_orders, only: %i[create]
      resources :search, only: %i[index]
      resources :addresses, only: %i[index create destory]
      resources :pharmacy_sessions, only: %i[create]

      # Specific to pharmacies => get orders and classify them
      resources :pharmacy_pending_orders, only: %i[index]
      resources :pharmacy_finished_orders, only: %i[index create]
      resources :pharmacy_not_found_orders, only: %i[create]
      resources :pharmacy_fake_orders, only: %i[create]

      # Specific to the owner => monitor all pharmacies work
      resources :pending_orders, only: %i[index]
      resources :finished_orders, only: %i[index]
      resources :fake_orders, only: %i[index]
      resources :not_found_orders, only: %i[index]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  include ImageUploader::Attachment(:image)
  has_many :medications
end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < Api::V1::VersionOneController
      before_action :set_category, only: %i[show]
      # GET Categories/
      def index
        if params[:lang] == 'ar'
          render json: Category.all
        else
          render json: Category.all
        end
      end

      # GET Categories/1
      def show
        if params[:lang] == 'ar'
          render json: @category.medications.order('name ASC').offset(params[:offset]).limit(12)
        else
          render json: @category.medications.order('name ASC').offset(params[:offset]).limit(12)
        end
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_admin!, except: [:show]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    # render json: @categories
  end

  # GET /categories/1 or /categories/1.json
  def show
    @medications = @category.medications
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:id, :name, :img, :image)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if category.image %>
      <%= image_tag category.image_url, style: "width:200px;" %>
    <% end %>

    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Img</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td> <%= image_tag category.image_url, style:'max-height:50px' if category.image %></td>
       
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

</div>

app/views/categories/new.html.erb
<div class="container">

    <h1>New Category</h1>

    <%= render 'form', category: @category %>
    <%= link_to 'Back', categories_path %>
    
</div>

app/views/categories/show.html.erb
<br><br>
<div class="container max-width3 meds">
    <% @medications.each do |medication| %>
      <%= link_to medication_path(medication.id), class:"card-link m-auto" do %>
        <div class="card en">
          <div class="p-1 pb-0 product-img ">
          <%= image_tag medication.img if medication.img %>  
          </div>
          <div class="product-info p-2 pt-0">
            <h6 class="card-title"><b><%= medication.name %></b></h6>
            <h6 class="card-text "><i><%= medication.shape %></i></h6>
            <span class="card-text bg-warning px-1 rounded"><%= medication.price %> EGP</span>
          </div>
        </div>
      <% end %>
    <% end %>
</div>
<br><br>
<br><br>