config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :pharmacies
  resources :cosm_meds do
    collection do
      post :import
    end
  end
  resources :cosm_cats
  resources :orders
  resources :categories
  root 'app#index'
  get '/cats', to: 'app#cats'
  get '/prescription', to: 'app#prescription'
  post '/n_prescription', to: 'app#n_prescription'

  get '/checkout', to: 'app#checkout'
  post '/new_order', to: 'app#new_order'
  get '/sales', to: 'orders#sellings'
  post '/sold/:id', to: 'orders#sell'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :medications do
    collection do
      post :import
    end
  end
  resources :cart_items
  get '/cosm_cats/cat/:name', to: 'cosm_cats#cats'
  get '/search', to: 'search#index'
  post '/search', to: 'search#index'

  namespace :api do
    namespace :v1 do
      # Specific to user
      devise_for :users, controllers: { registrations: 'api/v1/registrations' }
      resources :categories, only: %i[index show]
      resources :medications, only: %i[show]
      resources :cosmetics_categories, only: %i[index show]
      resources :cosmetics, only: %i[show]
      resources :cart_items, only: %i[index show create update destroy]
      resources :order_items, only: %i[index]
      resources :orders, only: %i[index create]
      resources :text_orders, only: %i[create]
      resources :img_orders, only: %i[create]
      resources :search, only: %i[index]
      resources :addresses, only: %i[index create destory]
      resources :pharmacy_sessions, only: %i[create]

      # Specific to pharmacies => get orders and classify them
      resources :pharmacy_pending_orders, only: %i[index]
      resources :pharmacy_finished_orders, only: %i[index create]
      resources :pharmacy_not_found_orders, only: %i[create]
      resources :pharmacy_fake_orders, only: %i[create]

      # Specific to the owner => monitor all pharmacies work
      resources :pending_orders, only: %i[index]
      resources :finished_orders, only: %i[index]
      resources :fake_orders, only: %i[index]
      resources :not_found_orders, only: %i[index]
    end
  end
end

app/models/cosm_med.rb
class CosmMed < ApplicationRecord
  include ImageUploader::Attachment(:image)
  belongs_to :cosm_cat

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :category, presence: true
  validates :sub_category, presence: true
  validates :price, presence: true
  validates :img, presence: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      r = row.to_hash
      med = CosmMed.new name: r['name'], price: r['price'], img: r['img'], category: r['category'], sub_category: r['sub_category']
      if med.category && med.sub_category
        cat = CosmCat.find_by('lower(name) = ?', med.sub_category.downcase)
        if cat
          med.cosm_cat_id = cat.id
        else
          cat = CosmCat.create(name: med.sub_category, parent: med.category)
          med.cosm_cat_id = cat.id
        end
      end
      med.availability = "true"
      med.save
    end
  end
end

app/controllers/cosm_meds_controller.rb
# frozen_string_literal: true

class CosmMedsController < ApplicationController
  before_action :set_cosm_med, only: %i[show edit update destroy]
  before_action :authenticate_admin!, except: [:show]

  # GET /cosm_meds or /cosm_meds.json
  def index
    @cosm_meds = CosmMed.all
  end

  def import
    CosmMed.import(params[:file])
    redirect_to root_url, notice: 'Upload done!'
  end

  # GET /cosm_meds/1 or /cosm_meds/1.json
  def show
    @cart = CartItem.new
    @medication = CosmMed.find(params[:id])
  end

  # GET /cosm_meds/new
  def new
    @cosm_med = CosmMed.new
    @cosm_cats = CosmCat.all
  end

  # GET /cosm_meds/1/edit
  def edit
    @cosm_cats = CosmCat.all
  end

  # POST /cosm_meds or /cosm_meds.json
  def create
    @cosm_med = CosmMed.new(cosm_med_params)
    cat = CosmCat.find(@cosm_med.cosm_cat_id)
    @cosm_med.category = cat.name
    @cosm_med.sub_category = cat.parent
    @cosm_med.img = JSON.parse(@cosm_med.image_data)['id'] if @cosm_med.image_data

    respond_to do |format|
      if @cosm_med.save
        format.html { redirect_to cosm_meds_path, notice: 'تمت الاضافة بنجاح!' }
        format.json { render :index, status: :created, location: @cosm_med }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cosm_med.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cosm_meds/1 or /cosm_meds/1.json
  def update
    respond_to do |format|
      if @cosm_med.update(cosm_med_params)
        format.html { redirect_to @cosm_med, notice: 'تم حذف المنتج بنجاح!' }
        format.json { render :show, status: :ok, location: @cosm_med }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cosm_med.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cosm_meds/1 or /cosm_meds/1.json
  def destroy
    @cosm_med.destroy
    respond_to do |format|
      format.html { redirect_to cosm_meds_url, notice: 'Cosm med was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cosm_med
    @cosm_med = CosmMed.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cosm_med_params
    params.require(:cosm_med).permit(:name, :description, :cosm_cat_id, :image, :img, :quantity, :price, :discount)
  end
end

app/helpers/cosm_meds_helper.rb
# frozen_string_literal: true

module CosmMedsHelper
end

app/views/cosm_meds/_form.html.erb
<%= form_with(model: cosm_med) do |form| %>
<% if cosm_med.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(cosm_med.errors.count, "error") %> prohibited this cosm_med from being saved:</h2>

    <ul>
        <% cosm_med.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>
<br>
<div class="field form-gruop">
    <%= form.label 'اسم المستحضر' %>
    <%= form.text_field :name, class:"form-control" %>
</div>
<br>
<div class="field form-gruop">
    <%= form.label 'السعر' %>
    <%= form.text_field :price, class:"form-control" %>
</div>
<br>
<div class="field form-gruop">
    <%= form.label 'الاسم بالعربي' %>
    <%= form.text_area :description, class:"form-control" %>
</div>
<br>
<div class="field form-gruop">
    <%= form.label "القسم" %>
    <%= select_tag "cosm_med[cosm_cat_id]", options_from_collection_for_select(CosmCat.all, :id, :name, cosm_med.cosm_cat_id), class:"form-control" %>
</div>
<br>
<div class="field form-gruop">
    <%= form.label 'الصورة' %>
    <%= form.file_field :image, class:"form-control" %>
</div>
<br>
<div class="field form-gruop">
    <%= form.label "الكمية المتاحة" %>
    <%= form.number_field :quantity, class:"form-control" %>
</div>
<br>
<div class="field form-gruop">
    <%= form.label 'الخصم' %>
    <%= form.number_field :discount, class:"form-control" %>
</div>
<br>
<div class="field form-gruop">
    <%= form.submit 'اضافة المستحضر ناااو', class:"btn btn-success" %>
</div>
<% end %>

<br><br><br><br>

app/views/cosm_meds/edit.html.erb
<br>
<div class="max-width2 m-auto p-4">
    <h1>تعديل بيانات المستحضر</h1>

    <%= render 'form', cosm_med: @cosm_med %>

    <%= link_to 'Show', @cosm_med %> |
    <%= link_to 'Back', cosm_meds_path %>
</div>

app/views/cosm_meds/index.html.erb
<h1 class="m-3">مستحضرات التجميل</h1>

<br><br>
<%= link_to 'اضافة جديد', new_cosm_med_path, class:"btn-success btn m-3" %>
<br>

<h4>Import bulk data</h4>
<%= form_tag import_cosm_meds_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
<% end %>

<br>
<table class="table table-striped m-2" style="font-size:15px;">
    <thead>
        <tr>
            <th>الاسم</th>
            <th>الاسم بالعربي</th>
            <th>السعر</th>
            <th>القسم</th>
            <th>الصورة</th>
            <th>الكمية</th>
            <th>الخصم</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @cosm_meds.each do |cosm_med| %>
        <tr>
            <td><%= cosm_med.name %></td>
            <td><%= cosm_med.description %></td>
            <td><%= cosm_med.price %></td>
            <td><%= cosm_med.cosm_cat.name %></td>

            <% if cosm_med.image %>
                <td><%= image_tag cosm_med.image_url, style:"height:50px;" %></td>
            <% elsif cosm_med.img %>
                <td><img src="<%= cosm_med.img %>" style='height: 50px' /></td>
            <% else %>
                <td>-</td>
            <% end %>
            <td><%= cosm_med.quantity %></td>
            <td><%= cosm_med.discount %></td>
            <td><%= link_to 'عرض', cosm_med, class:"btn btn-secondary" %></td>
            <td><%= link_to 'تعديل', edit_cosm_med_path(cosm_med), class:"btn btn-warning" %></td>
            <td><%= link_to 'حذف', cosm_med, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br><br><br><br>

app/views/cosm_meds/new.html.erb
<br>
<div class="max-width2 m-auto p-4">
    <h1>اضافة مستحضر جديد</h1>

    <%= render 'form', cosm_med: @cosm_med %>

    <%= link_to 'Back', cosm_meds_path %>
</div>

app/views/cosm_meds/show.html.erb
<div class="max-width2 center show p-2 position-relative">
    <br><br>

    <%= image_tag @medication.image_url, class:'show-img' if @medication.image %>
    <%= image_tag @medication.img, class:'show-img' if !@medication.image && @medication.img%>
    <hr>
    <h6 class="flex-row">
        <strong> <%= @medication.name %> </strong>
    </h6>
    <p class="show-price">ج-م <%= @medication.price %></p>

    <div class="row w-100 text-left m-auto">
        <div class="col-4">
            <strong>
                <p>الوصف:</p>
            </strong>
        </div>
        <div class="col-8">
            <p><%= @medication.description %></p>
            <br>
        </div>
    </div>


    <div class="row w-100 text-left m-auto">
        <button type="button" class="btn btn-success btn-block btn-lg m-0 add-to-cart">اضافة للعربة <i class="fa fa-shopping-cart color-white"></i></button>
    </div>

    <div class="position-absolute mod">
        <div>
            <%= form_with(model: @cart) do |form| %>
            <div class="field my-3">
                <button type="button" class="min btn btn-danger"> <i class="fa fa-minus color-white"></i></button>
                <%= form.number_field :quantity, class:"form-control mx-3", value:1, min:1 %>
                <button type="button" class="add btn btn-success"> <i class="fa fa-plus color-white"></i></button>
            </div>
            <%= form.hidden_field :item_id, value: @medication.id %>
            <div class="actions w-100">
                <%= form.submit "اضافة", class:"btn btn-success my-1 w-100"%>
                <button type="button" class="btn btn-secondary my-1 w-100 close-mod">اغلاق</button>
            </div>
            <% end %>
        </div>
    </div>

</div>

<br><br><br>